name: Cppcheck-action-test

on: [push]
  push:
 
jobs:
  build:
   name: cppcheck-test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: 
    - name: make-C 3_Implementation
 
